title: Sergey's Blog
description: A software engineer writing about native mobile and AI-assisted development, and software engineering in general.
url: "https://sergenes.github.io"
author: Sergey Neskoromny

theme: minima

minima:
  skin: auto

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

show_excerpts: true

markdown: kramdown
highlighter: rouge
